### ISSUE TITLE
Move `AWSTestServer` to extra target `AWSSDKTestUtils`

### ISSUE THREAD

**Issue by fabianfett** [swift-aws/aws-sdk-swift-core#267]
We would like to make the `AWSTestServer` more accessible.

- [x] Create a new target `AWSSDKTestUtils`
- [x] Move the `AWSTestServer` into the new target and rename to `MockServer` maybe? @adam-fowler 
- [x] Fix all broken tests

**Comment by Ro-M** [comment]
Hi @adam-fowler. I looked into this issue. The AWSTestServer is currently using the `XMLDecoder` and `XMLEncoder`. Those classes (from AWSSDKSwiftCore) are internal and cannot be used in another target.

Using the decoder/encoder is currently possible because the AWSSDKSwiftCore is imported via `@testable`. Is it ok to keep this annotation in a non-testTarget? Or can the encoder/decoder be made public?

**Comment by adam-fowler** [comment]
Hi @Ro-M , 

I'm currently refactoring some of this. Can you hold off on this. The xml decoder/encoder will probably be made public again for other reasons in near future. So this shouldn't be an issue. I hadn't realised you were looking into these already. If you are looking for something to start on, would you be able to look at #266 or #268. Also you could add a PR to make the XML encoder/decoder public. Not particularly complex I must admit.

**Comment by adam-fowler** [comment]
I'm happy with `AWSTestServer`

**Comment by fabianfett** [comment]
@adam-fowler i'm good with `AWSTestServer` as well.
