### ISSUE TITLE
tests don't run in release mode

### ISSUE THREAD

**Issue by weissi** [swift-aws/aws-sdk-swift-core#43]
I got this compilation failure when running the tests with

    swift test --sanitize=address -c release -Xswiftc -enable-testing

which we do as part of the SwiftNIO compatibility/test suite before releases.

```
Compile Swift Module 'AWSSDKSwiftCore' (29 sources)
Compile Swift Module 'AWSSDKSwiftCoreTests' (9 sources)
/private/tmp/.nio-release-tools_z0dmMg/aws-sdk-swift-core/Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift:39:34: error: value of type 'AWSClient' has no member 'debugCreateAWSRequest'
            let awsRequest = try sesClient.debugCreateAWSRequest(
                                 ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
/private/tmp/.nio-release-tools_z0dmMg/aws-sdk-swift-core/Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift:66:34: error: value of type 'AWSClient' has no member 'debugCreateAWSRequest'
            let awsRequest = try kinesisClient.debugCreateAWSRequest(
                                 ^~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
error: terminated(1): /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /private/tmp/.nio-release-tools_z0dmMg/aws-sdk-swift-core/.build/release.yaml test output:
```

**Comment by jonnymacs** [comment]
@weissi hmm... yeah this is to maintain the fileprivate status of createAWSRequest method in release mode. The public debug method is added as an extension when the Debug directive is set

`-Xswiftc -DDEBUG`

is this an option for you to add?

**Comment by weissi** [comment]
@jonnymacs sure, that's fine. Just out of interest, why don't you make it `internal` ?

**Comment by jonnymacs** [comment]
@weissi it's a good question.  I didn't define the original access control for createAWSRequest, that was @noppoMan, so he may provide a better answer. But I imagine it's because internal still allows for exposing the method through an extension in another part of the code and we want to restrict all access to this method to just this file.

Using the DEBUG directive to add an internal debug method that is exposed with @testable seemed like a nice workaround to preserve the fileprivate access control while still adding some tests. (note - i misspoke in my prev comment, debugCreateAWSRequest is not public)

**Comment by Yasumoto** [comment]
I don't think we've needed this, so sent out https://github.com/swift-aws/aws-sdk-swift-core/pull/134

**Comment by adam-fowler** [comment]
fixed

**Comment by weissi** [comment]
thank you! I will change the nio release tools to run aws core with release mode too :)
